### ISSUE TITLE
3D at the top

### ISSUE THREAD

**Issue by EnriqueMVega** [facebook/Surround360#100]
I was told that is not possible to have 3D at the top of the 360 video but I just found this http://www.vrcolony.net/tutorialsblog/2015/9/19/3-camera-zenith-for-better-3d It makes sense to me. Can I get your opinion on this?

**Comment by fbriggs** [comment]
It doesn't matter how you arrange the cameras or what the stitching is- 3D will not be perfect at the top or bottom no matter what. The reason has to do with the whole "omni-directional stereo" format. Each column of pixels in the equirect image is correct for a particular head orientation. When you are looking at the horizon, you see only columns of pixels that are for your current head orientation and others that are similar. However, if you are looking too close to the top, you will see some columns of pixels that are appropriate for your current head orientation, and some that are for a 180-degree opposite head orientation, which will give backward depth cues.

It is true that you can get the stereo part of the panorama to go higher up than our current system, which provides only a 77 degree strip of stereo at the horizon.
