### ISSUE TITLE
Is there a way to turn off stereo rendering?

### ISSUE THREAD

**Issue by knottb** [facebook/Surround360#101]
The images I am producing with run_all.py all have similar issues. parts of the image will be perfect in one eye, but poor optical flow in the other eye. 
(Calibration has been done)

I am wondering if there is an option for mono rendering.

Thanks.

**Comment by fbriggs** [comment]
In batch_process_video.py, line 45, if you change
--interpupilary_dist 6.4
to
--interpupilary_dist 0.0
It will be mono (althought you will still get 2 copies, one for left eye + one for right). The software was not designed for mono really.
