### ISSUE TITLE
http://127.0.0.1:8090 failed

### ISSUE THREAD

**Issue by BroadDong** [facebook/Surround360#106]
Now I run into a problem as shown below.Could you tell me how I should solve?
![2016-09-19 19_52_48____________](https://cloud.githubusercontent.com/assets/20699811/18615539/d0f5ffb6-7ddb-11e6-8456-b0ceaf28c269.png)

**Comment by dangsiper** [comment]
Hi @BroadDong 
Would you please leave your email, then we can exchange our info more convenient.

**Comment by BroadDong** [comment]
@dangsiper ，1418592293@qq.com

**Comment by dangsiper** [comment]
Hi @BroadDong 
This problem may be caused by you haven't ran ffserver.
You should first run:
<code>
ffserver -f configs/ffserver.conf&
</code>
, then run the CameraControl program.

**Comment by aparrapo** [comment]
@BroadDong did @dangsiper 's suggestion fix your issue?

**Comment by aparrapo** [comment]
This version of the camera capture is no longer on the repo. Closing this issue :)
