### ISSUE TITLE
web服务器

### ISSUE THREAD

**Issue by BroadDong** [facebook/Surround360#108]
When I run the camera_control,there is the issue as shown below.Should I set up web server?And how?
![2016-09-21 11 24 03](https://cloud.githubusercontent.com/assets/20699811/18656581/ed9662e2-7f24-11e6-9da2-3540649b575d.png)
![2016-09-21 11 24 17](https://cloud.githubusercontent.com/assets/20699811/18656584/f21b624a-7f24-11e6-9b0c-e904bfd2932b.png)

**Comment by dangsiper** [comment]
@BroadDong 
There are two way to view preview stream:

* First set up a web server which supports PHP, then configure the server's root to "Surround360\surround360_camera_ctl\source\www\camera_capture" or copy these files to the server's default root(It is maybe locate at /var/www/html/). At last, access URL http://127.0.0.1 and start preview.

* Direct access URL http://127.0.0.1:8090/live.webm

**Comment by mybuddyhoward** [comment]
@BroadDong and @dangsiper , I'm stuck on the part of running the Camera Control software. It's throwing an error of an instance of "std::string". Seems you both have gotten further than I have. Would either of you be able to help me. You can email me @ howard@reverge.com.
Thanks in advance.

**Comment by dangsiper** [comment]
@mybuddyhoward please refer to https://github.com/facebook/Surround360/issues/93

**Comment by aparrapo** [comment]
#93 and #127 seem to solve this issue. Closing this one for now.
