### ISSUE TITLE
220 fisheye rectification

### ISSUE THREAD

**Issue by mimiaofandisp** [facebook/Surround360#109]
How to do rectification for 220 fisheye images?
I did fisheye to spherical projection and then run the rectification code, the result is terrible. But I cannot do undistortion-->rectify-->spherical, that will lose too much image content.
Any ideas?

**Comment by fbriggs** [comment]
Sorry, but the rectification code we have doesn't support fisheye lenses. It assumes the side lenses are rectilinear (after correcting for barrel distortion), and the rectilinear camera model doesn't work for anything above 180 degrees (and practically, probably not much above 120).
