### ISSUE TITLE
How do we get the vedios from cameracontrol?

### ISSUE THREAD

**Issue by DxgHandInHand** [facebook/Surround360#112]
When I ran “ffserver -f configs/ffserver.conf ” and “sudo ./CameraControl --nframes 5 --raw –nbits 8 --brightness 1 --shutter 20.0 --gain 0 --fps 30 --numcams 1 --debug”, I met the situation in the image.
Could you tell me how I get the videos in some detail?
![109](https://cloud.githubusercontent.com/assets/20218626/18826840/17c2bc96-8402-11e6-9871-06da28fc8fec.jpg)
![110](https://cloud.githubusercontent.com/assets/20218626/18826845/19d0a4b2-8402-11e6-98ef-5aa1c7e8b933.jpg)

**Comment by mybuddyhoward** [comment]
Hey @DxgHandInHand 
Were you able to figure out how to get the videos?

**Comment by aparrapo** [comment]
@DxgHandInHand this version of the capture software is no longer part of the repo. Can you try with the new version? Closing this issue for now, but feel free to open a different one if you still have problems.
