### ISSUE TITLE
Suggestion for Rectification Improvement

### ISSUE THREAD

**Issue by ccdunnyv** [facebook/Surround360#114]
We are finding that when we turn on rectification, we are getting a lot of bogus results when we have images with repeating textures, like the gridded holes in some fluorescent light fixtures. One thing that might help is to restrict the original feature detection to be within the valid range, given the horizontal FOV of the cameras. For example, we are getting bogus rectification results where many keypoints from outside the possible overlapping region between two images (given the FOV) are matching to each other. I assume you are calling some OpenCV commands to do the rectification, but you could apply this improvement by simply horizontally cropping the two images to their overlapping region. Hope that makes sense...

**Comment by fbriggs** [comment]
You are right.. it should be possible to improve keypoint matching by rejecting matches that are too far from plausible. We try to do some of this already by applying RANSAC.

One thing to keep in mind is that you don't necessarily need to do rectification every time. If you have a rigid camera, and you get it to work on one scene, you can use that rectify.yml file for other scenes with the same camera.
