### ISSUE TITLE
About the Surrount360 device design question--Hardware （二）

### ISSUE THREAD

**Issue by brownliang** [facebook/Surround360#115]
Hi Facebook：
                 Thaks for your reply and the detailly description about the issue of “About the Surrount360 device design question--Hardware“.Sorry for the replying lately for mey business trip.I still have the last question.
![00](https://cloud.githubusercontent.com/assets/20677537/18978736/2426837a-86f8-11e6-9a20-4ebd15ce8359.jpg)
               1. As we know, the fov of point gray camera is the 77°（this is diagonal value），as the picture ration H:V is 1:1。So we can calculate the horizontal FOV is 54.5°。
               2.From his  formula i = r * sin(FOV/2 - 360/n) 。We can get the i =21*sin(54.5/2-360/14)=0.56cm.
               3.So,i is less than 3.2cm. It can't match the requiement.
               PS: If I put the diagonal fov into this formula, i =21*sin(77/2-360/14)=4.65cm.It can meet the design requirement.
                Thank you!

**Comment by fbriggs** [comment]
The FOV of the point grey camera (CMOSIS sensor with Sunex lens) is not 77 degrees diagonal. It is 77 degrees horizontal, after correcting barrel distortion.
