### ISSUE TITLE
sample dataset?

### ISSUE THREAD

**Issue by nsmulay** [facebook/Surround360#119]
Is it possible to get more sample datasets: more frames, more sequences? Need to test/try out something and would need more than currently available data which has only 2 frames worth of "Palace of Fine Arts". If not raw, just isp out should also be fine.

**Comment by fbriggs** [comment]
Sorry for the delay. I just uploaded a full 1 minute RAW binary dataset. It's linked on the front page of the repo.

**Comment by nsmulay** [comment]
Great, thanks a lot!
