### ISSUE TITLE
some papers to help understand the render algorithm?

### ISSUE THREAD

**Issue by LiCong1992** [facebook/Surround360#120]
Hi I'm trying to study the algorithms you guys used in the rendering algorithms, but I'm having some troubles understanding them. So can you offer me some papers or links? 
Thanks a lot!

**Comment by fbriggs** [comment]
Our approach is closely related to some of Disney's work from 2013:
"Megastereo: Constructing High-Resolution Stereo Panoramas"
http://www.ahornung.net/files/pub/2013-cvpr-megastereo-richardt.pdf

Also Google just recently published a paper about software for JUMP, which is quite similar:
https://research.google.com/pubs/pub45617.html
