### ISSUE TITLE
How to create a new intrinsic parameters file?

### ISSUE THREAD

**Issue by dangsiper** [facebook/Surround360#122]
Hi,
I get a new camera and captured a picture as the attachment:
![img_0_raw8](https://cloud.githubusercontent.com/assets/8447647/19472405/be00303a-9559-11e6-959a-c96abecacc0f.png)
the attachment is a bmp picture, I change it suffix name to upload.

When I run this command to create intrinsic parameters file, it can't find the checkerboard:
```
bin/TestIntrinsicCalibration \
--logbuflevel -1 --stderrthreshold 0 --v 0 \
--mode build_intrinsic_model \
--checkerboard_width 9 \
--checkerboard_height 12 \
--resize_width 2448 \
--resize_height 2048 \
--checker_size 50.0 \
--sensor_width 14.0 \
--sensor_height 14.0 \
--src_checkerboards_dir ~/Desktop/intrinsic/src \
--dest_param_file ~/Desktop/intrinsic/my_intrinsic.xml
```
Is there some parameters I need to change?
Thanks in advance.

**Comment by fbriggs** [comment]
Try this:
--checkerboard_width 8 \
--checkerboard_height 11 \

Opencv measures the dimensions of the checkerboard using only interior corners.
