### ISSUE TITLE
gpu version

### ISSUE THREAD

**Issue by cvaldesmol** [facebook/Surround360#129]
Hi there
I just want to say good work. The code has allowed me to learn a lot. 
Do you plan to start working on the gpu version soon? I tested the code and works fine but we need speed. Thanks a lot

**Comment by fbriggs** [comment]
We have explored GPU implementations of some parts of the system. However, it is not always trivial to make the GPU version faster than the CPU version. For example, we implemented optical flow on GPU and it was faster when running in a standalone test, but when running in the actual rendering pipeline it needs to do many flow problems in parallel threads, but they end up being executed sequentially by the GPU. To set some realistic expectations, some parts of the code may be implemented on GPU soon, where it is practical and beneficial, but it is not likely that the whole system will be rewritten on GPU soon.
