### ISSUE TITLE
Should both HFOV and VFOV match i > 3.2cm with i = r * sin( FOV/2 - 360 / n) > 3.2

### ISSUE THREAD

**Issue by ted51** [facebook/Surround360#130]
Hi fbriggs,

The hfov of our rig is 72°. The vfov is 58.9°.  With hfov, we can have  i > 3.2cm, while with vfov, we can't.  Should both hfov and vfov match i > 3.2cm, or just hfov?

thanks
Ted

**Comment by fbriggs** [comment]
For the purpose of calculating if a rig design can work with our software, the formula i = r * sin(FOV/2 - 360/n) refers to the horizontal fov. The vertical fov doesn't matter here.
