### ISSUE TITLE
How to remove 2448*2048 picture's pole?

### ISSUE THREAD

**Issue by dangsiper** [facebook/Surround360#135]
Hi,

We try to remove our picture's pole, but it seems doesn't work. Our picture's dimension is 2448*2048.
Below is our pic don't remove pole:

![eqr_000000_pole](https://cloud.githubusercontent.com/assets/8447647/20213872/b4c6ab12-a845-11e6-9bca-cb09b6c5f93b.jpg)
We used files in "res/pole_masks" to remove pole. Below is our pic remove pole:

![eqr_000000](https://cloud.githubusercontent.com/assets/8447647/20213908/e246a5e2-a845-11e6-8daf-8d35d4819e68.jpg)

Below is our original pic:
![cam15 2](https://cloud.githubusercontent.com/assets/8447647/20213943/1622e72c-a846-11e6-90de-4605c924230e.png)
![cam16 2](https://cloud.githubusercontent.com/assets/8447647/20213944/16917d5e-a846-11e6-9a68-66d2ee864987.png)
Is there any way to resolve this?
Thanks in advance.

**Comment by aparrapo** [comment]
You have to create a mask around the pole and put those files in "res/pole_masks". See the example below:

![pole1](https://cloud.githubusercontent.com/assets/7462577/20221495/6e536b2a-a7e6-11e6-8541-f404084ef551.png)
![pole2](https://cloud.githubusercontent.com/assets/7462577/20221496/6e6d2a38-a7e6-11e6-9978-f4edb8e4ce6d.png)

**Comment by dangsiper** [comment]
@aparrapo Thanks so much for your help.
We can remove the pole now.
