### ISSUE TITLE
The issue of the install control2

### ISSUE THREAD

**Issue by BroadDong** [facebook/Surround360#136]
![2016-11-16 15 01 53](https://cloud.githubusercontent.com/assets/20699811/20337841/71160404-ac0e-11e6-96c0-63918c488667.png)
Why？How could I do?

**Comment by tellyarz** [comment]
Is your OS version 14? We had similar problem too until we switched to OS version 16. Seems libgtkmm-3.0-1v5 requires packages not found in version 14 but in version 16

**Comment by BroadDong** [comment]
My system is Ubuntu14.04

**Comment by emmanix2002** [comment]
@BroadDong you need to have Ubuntu 16.04 to build CameraControl2. The packages that gave you issues are available on >= 16.04. We ended up upgrading to 16.04 so we could setup CameraControl2.

**Comment by BroadDong** [comment]
@emmanix2002 ，thank you very much！I have update it.But I encounter the problem，as follows.Could
you tell me how to solve it? I can't find the "CameraIspGen8.h".
![2016-11-20 19-15-58](https://cloud.githubusercontent.com/assets/20699811/20462355/7fd54f5e-af56-11e6-93f3-aaed6fe530da.png)

**Comment by emmanix2002** [comment]
@BroadDong the solution to that is as follow: 

- you'll need to setup `Halide` on your machine; you should build it yourself -- don't use the precompiled binaries; you'll run into an issue with that. This is covered in the setup instructions for the `surround360_render`.    
- Build `surround360_render` again, this time providing the `DHALIDE_DIR` which should point to the `cmake_build` inside the Halide directory - assuming you built Halide using `cmake`

After you've done the above, the required files will be created.

**Comment by aparrapo** [comment]
Thanks @emmanix2002 for your input. Closing this for now. @BroadDong please reopen and comment if you still have problems.
