### ISSUE TITLE
Can't find "the CameraIspGen8.h"

### ISSUE THREAD

**Issue by BroadDong** [facebook/Surround360#138]
Could you tell me how to solve it? I can't the "CameraIspGen8.h".And I think that the other header files are not found ,for example the CameraIspGenFast8.h, CameraIspGen16.h, CameraIspGenFast16.h and Halide.h.
![2016-11-20 19-15-58](https://cloud.githubusercontent.com/assets/20699811/20462377/5824e9f0-af57-11e6-9e71-566e7c18ea55.png)

**Comment by emmanix2002** [comment]
@BroadDong see my response in issue #136

**Comment by aparrapo** [comment]
Closing for now. #136 should take care of this.
