### ISSUE TITLE
Stereoscropic coverage

### ISSUE THREAD

**Issue by BroadDong** [facebook/Surround360#14]
What is the degree of three-dimensional coverage?Why is the Centerline+/- 144(h), 77(v)degrees?

**Comment by BroadDong** [comment]
What is the degree of stereoscopic  coverage?Why is the Centerline+/- 144(h), 77(v)degrees?

**Comment by bkcabral** [comment]
It's 77 degrees after pinhole rectification.  That's just what that 90deg FOV lens produces.

**Comment by BroadDong** [comment]
The importance is  the Centerline +/- 144(h). It's not  +/- 180(h). Why?

**Comment by BroadDong** [comment]
The importance is  the Centerline +/- 144(h). It's not  +/- 180(h). Why?
