### ISSUE TITLE
Can't record from the  CameraControlUI?

### ISSUE THREAD

**Issue by BroadDong** [facebook/Surround360#142]
when I get the CameraControlUI，but I can't record.And I only gain the one picture from the first camera.Please tell me Why? Thank you very much. 
![2016-11-25 12-54-37](https://cloud.githubusercontent.com/assets/20699811/20600415/8f3b67e0-b28e-11e6-8874-ad54543b4649.png)

**Comment by emmanix2002** [comment]
@BroadDong that is just the preview window. It shows you the "view" from the selected camera; since you have all 17 cameras connected, recording takes data from all 17 of them and writes it to your output directory. You can confirm this by looking at the output after using `surround360_render`.

**Comment by aparrapo** [comment]
@BroadDong, closing this issue for now, but let us know if the problem persists :)

**Comment by lcyzzz** [comment]
Hi @BroadDong, I have the same problem with yours and I  want to know did you fix this problem?
