### ISSUE TITLE
Feed pre-rendered equirectangular into the renderer for optical flow

### ISSUE THREAD

**Issue by TomHVR** [facebook/Surround360#143]
Is there a way to feed individual image sequences or video into the system that have already been warped/distorted into latlong space? 

I am interesting in comparing the optical flow performance against the Foundry's CARAVR ocula stitcher which is a 10 000 USD software package.

**Comment by fbriggs** [comment]
There is no way to feed in images that are already warped into latlong space. A feature like that could be added with changes to the code (I'd guess about ~100 lines change; this would replace the call here https://github.com/facebook/Surround360/blob/master/surround360_render/source/test/TestRenderStereoPanorama.cpp#L80 to projectCamImageToSphericalThread).
