### ISSUE TITLE
Fatal Error on compiling CameraControlUI Software

### ISSUE THREAD

**Issue by jiangjingping** [facebook/Surround360#146]
![desctop screenshot](https://cloud.githubusercontent.com/assets/14227549/20791038/0fff326e-b7f6-11e6-9a68-157a1f9c769d.png)
I don't know why this error occurred , I have installed the following packages:
   libgtkmm-2.4-1c2a libgtkmm-2.4-dev libgtkmm-3.0-1 libgtkmm-3.0-dev
waiting for help ..

**Comment by emmanix2002** [comment]
`glarea.h` was added in `libgtkmm-3.0-1v5` meaning you need to be running `>= Ubuntu 16.04` since the package is only available in Ubuntu16.04 and greater.
Hope this helps.

**Comment by jiangjingping** [comment]
@emmanix2002 :  I tried , it worked !  thanks a lot !!
