### ISSUE TITLE
Temporal coherence

### ISSUE THREAD

**Issue by yzpick** [facebook/Surround360#150]
Hi, can you explain a bit about how you maintain temporal coherence? I cannot quite understand how you use previous flow to do Temporal Regularization. Thanks!

**Comment by fbriggs** [comment]
There is no temporal regularization on the first frame. On every frame, it saves the results of flow, and the images that are inputs to flow, into special folders inside the working directory for each frame. On each frame except the first, flow reads the previous frame's solution for flow, and the previous frame's input images. It computes a motion detection function by comparing the previous frame's input images to flow with the current frame's images. The while solving for the next frame's flow, it is weighted-averaged with the previous frame's flow, where the weight depends on the detection of motion (if there is no motion in the scene, there can be no change in the flow).
