### ISSUE TITLE
"fisheye_rotation_deg" parameter?

### ISSUE THREAD

**Issue by tlian7** [facebook/Surround360#163]
I was wondering how the "_fisheye_rotation_deg_" parameter should be set in the rig JSON file. Right now I'm simply adjusting the rotation manually until I feel like the output from the fisheye cameras aligns with the panorama created by the cameras around the circumference of the rig. This doesn't seem particularly accurate nor foolproof; is there a correct way to be doing this? (E.g. Should the fisheye cameras be rotated with a certain alignment to the cameras around the circumference? Is there some computational step I'm missing somewhere?)

Thank in advance for your help!

**Comment by fbriggs** [comment]
Adjusting it manually is the best you can do for now. We are releasing an update to calibration which will handle this automatically soon, but it isn't out yet.
