### ISSUE TITLE
unknown command line flag 'accelerate'

### ISSUE THREAD

**Issue by XQ1560** [facebook/Surround360#169]
Hi all,
i'm running Surround 360 - Process Dataset to test sample_dataset(2 frames). And then, i got a core dump error. Here are my error report and config.

-------- Sat Feb 11 2017 13:08:37 CST -------

python /home/dyq/Desktop/Surround360/surround360_render/scripts/run_all.py --rectify_file /home/dyq/Desktop/sample_dataset/rectify.yml --enable_top  --quality 6k --cubemap_height 0 --cam_to_isp_config_file /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/cam_to_isp_config.json --steps_isp  --steps_rectify  --nbits 8 --data_dir /home/dyq/Desktop/sample_dataset --rig_json_file /home/dyq/Desktop/Surround360/surround360_render/res/config/17cmosis_default.json --image_width 2048 --dest_dir /home/dyq/Desktop/sample_dataset --flow_alg pixflow_low --cubemap_format video --src_intrinsic_param_file /home/dyq/Desktop/Surround360/surround360_render/res/config/sunex_intrinsic.xml --start_frame 0 --save_debug_images  --steps_render  --enable_pole_removal  --verbose  --pole_masks_dir /home/dyq/Desktop/Surround360/surround360_render/res/pole_masks --cubemap_width 0 --enable_bottom  --enable_render_coloradjust  --image_height 2048 --frame_count 1

** ISP ** [Step 1 of 3]

 python /home/dyq/Desktop/Surround360/surround360_render/scripts/batch_process_isp.py --surround360_render_dir /home/dyq/Desktop/Surround360/surround360_render --root_dir /home/dyq/Desktop/sample_dataset --start_frame 0 --end_frame 0 --cam_to_isp_config_file /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/cam_to_isp_config.json --nbits 8  --verbose 

----------- [ISP] processing frame: 000000
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam3.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp3.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam3.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam7.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp7.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam7.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam0.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp0.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam0.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam4.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp4.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam4.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam12.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp12.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam12.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam8.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp8.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam8.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam9.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp9.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam9.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam10.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp10.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam10.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam1.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp1.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam1.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam5.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp5.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam5.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam16.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp16.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam16.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam6.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp6.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam6.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam15.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp15.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam15.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam14.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp14.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam14.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam11.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp11.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam11.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam2.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp2.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam2.png --output_bpp 8 --accelerate  
 /home/dyq/Desktop/Surround360/surround360_render/bin/Raw2Rgb --logbuflevel -1 --log_dir /home/dyq/Desktop/sample_dataset/logs --stderrthreshold 0 --input_image_path /home/dyq/Desktop/sample_dataset/vid/000000/raw/cam13.bmp --isp_config_path /home/dyq/Desktop/Surround360/surround360_render/res/config/isp/isp13.json --black_level_offset 0 --output_image_path /home/dyq/Desktop/sample_dataset/vid/000000/isp_out/cam13.png --output_bpp 8 --accelerate  
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
ERROR: unknown command line flag 'accelerate'
Process failed

ISP runtime: 0:00:00.125765

** RECTIFY ** [Step 2 of 3]

 /home/dyq/Desktop/Surround360/surround360_render/bin/TestRingRectification --logbuflevel -1 --stderrthreshold 0 --v 0 --rig_json_file /home/dyq/Desktop/Surround360/surround360_render/res/config/17cmosis_default.json --src_intrinsic_param_file /home/dyq/Desktop/Surround360/surround360_render/res/config/sunex_intrinsic.xml --output_transforms_file /home/dyq/Desktop/sample_dataset/rectify.yml --root_dir /home/dyq/Desktop/sample_dataset --frames_list 000000 --visualization_dir /home/dyq/Desktop/sample_dataset/rectify_vis 

I0211 13:08:37.213104  9034 TestRingRectification.cpp:71] intrinsic parameters and distortion coefficients:
I0211 13:08:37.213217  9034 TestRingRectification.cpp:72] [1269.580714263026, 0, 1019.454515457277;
 0, 1266.978951119106, 1023.418452916802;
 0, 0, 1]
I0211 13:08:37.213238  9034 TestRingRectification.cpp:73] [-0.3203872316005091, 0.09807279936742816, 0.0002792073519266573, -0.000301939521590532, -0.01352514480488489]
I0211 13:08:37.213244  9034 TestRingRectification.cpp:75] reading camera json file
I0211 13:08:37.213493  9034 TestRingRectification.cpp:82] removing top and side cameras from rig

![image](https://cloud.githubusercontent.com/assets/13413738/22851553/99ef92fa-f060-11e6-8c50-02fd96581e19.png)
![image](https://cloud.githubusercontent.com/assets/13413738/22851562/d2781c3c-f060-11e6-9a14-9201fa009f8b.png)

i'm leaning this for not long. Wish to get an answer soon. Thank you for your help in advance.

**Comment by aparrapo** [comment]
Hi @XQ1560: did you install Halide? It's needed to run the Raw2Rgb command with the "accelerate" flag, which will make the process super fast. If you do not want to use Halide, remove this line

https://github.com/facebook/Surround360/blob/master/surround360_render/scripts/batch_process_isp.py#L29

and try again (no need to recompile, it's just a Python script).

**Comment by XQ1560** [comment]
@aparrapo Thanks so much! i didn't install Halide. After removed the line, i got success. ^_^
