### ISSUE TITLE
frames for testing

### ISSUE THREAD

**Issue by EnriqueMVega** [facebook/Surround360#17]
So far the project looks great. Thanks a lot
Before we purchase the hardware I would like to test the render part. Are you able to share a set of frames (5 secs to 15 sec) from each camera so we can use it for testing?  I know it is a lot to ask but will really help us to understand what the software is doing.

**Comment by VRabbitHole** [comment]
Agree with OP .... are there any RAW camera files we can take through the rendering software while we're waiting for the hardware?

**Comment by vensuka** [comment]
Yep I think this will be great :)

**Comment by fotolesny** [comment]
+1

**Comment by sekibara** [comment]
it will be really helpful!  if worry about size, please post sample raw photos instead of video at first. thanks

**Comment by goldonkey** [comment]
Thanks for sharing  your intellegent work！Captured sample  raw data file is  a very important part for everyone to try the OP code.

**Comment by PaulBergmann** [comment]
Thank you for releasing this code to the public! I also think some test data would be highly useful to get a better understanding of the whole pipeline!

**Comment by fbriggs** [comment]
here are 2 frames from the palace dataset: https://fburl.com/399375715
we will provide a larger dataset ASAP

**Comment by VRabbitHole** [comment]
Just checked out the links on both threads and got this message:

Sorry, this page isn't available
The link you followed may be broken, or the page may have been removed.

**Comment by fbriggs** [comment]
sorry, bad link. try this one instead:
https://s3-us-west-2.amazonaws.com/surround360/sample/sample_dataset.zip
