### ISSUE TITLE
Halide isp version produce a black result

### ISSUE THREAD

**Issue by linming1247576468** [facebook/Surround360#170]
![cam2](https://cloud.githubusercontent.com/assets/8693963/22852949/e742ed8c-f082-11e6-9d39-16621056c1ff.png)
![cam3](https://cloud.githubusercontent.com/assets/8693963/22852950/e7b7505a-f082-11e6-913a-5f6e61a66e77.png)

I installed halide in my computer(ubuntu 16.04), and run the Raw2Rgb of surround360 to process the isp with 'accelerate' argument. But the result is a black photo as cam2 shown above (the raw picture is from sample_dataset). Then I add the 'fast' argument and get the right photo(cam3). I think the problem comes from the installation of halide in my computer but I can't find where it is. Does anyone meet the same problem? Thanks.

**Comment by bkcabral** [comment]
Already made a fix it should land soon.  Thanks for reporting the bug.
