### ISSUE TITLE
Object shape is different between Left an Right panorama

### ISSUE THREAD

**Issue by maqiang6** [facebook/Surround360#171]
We have designed a 3D360 system by ourselves refferring Surround360_design. We find that bundle adjustment will warp the image. The same object in different viewpoint is different which will cause the same object's shape in Left and Right panorama is different. This gives the bad experience in VR device which brings bad stereoperception and dizziness.

**Comment by maqiang6** [comment]
I want to know how to solve this problem, or  how to use bundle adjustment to calibrate cameras. We have do this indoor,whether we should put it outdoor for bundle

**Comment by aparrapo** [comment]
Cool. Let us know if you have problems again in the future. We will be more than happy to help :)

**Comment by electech6** [comment]
I am also working on a 3D360 system refferring Surround360. Contact me for sharing experience (QQ:810855028) if you like. @maqiang6
