### ISSUE TITLE
tinfo for OSX in Makefile?

### ISSUE THREAD

**Issue by tlian7** [facebook/Surround360#174]
I'm not sure if this is a typo in the `CMakeLists.txt` or intentional, but I noticed that the `tinfo` library is linked in `TestVignettingCalibration` without a `IF(NOT APPLE AND NOT MSVC)` check (line 566). On my OSX, this generated an error for me when running `make`, specifically

`ld: library not found for -ltinfo  `

Commenting out the `tinfo` in `TestVignettingCalibration` fixed this for me. Was I just missing a library or was this a small typo?

**Comment by mikeseven** [comment]
Just remove tinfo from cmakefile on Apple section.

--mike


________________________________

**Comment by aparrapo** [comment]
Hi @tlian7. Yes, it's a typo. Line 566 should be deleted. If you want you can make a pull request so we can give you proper recognition :)
