### ISSUE TITLE
Script to mount RAID missing

### ISSUE THREAD

**Issue by Max-R7** [facebook/Surround360#180]
1) The Script for mounting the RAID at media/snoraid has been deleted and is therefore missing
2) The Script to reset USB Controllers has also been deleted

**Comment by aparrapo** [comment]
Hi @Max-R7, these scripts were used on the old version of the camera control software. The new version does not expect the RAID to be mounted on media/snoraid. You choose the location were you want to save the files via the capture UI.

The new UI also has the USB reset functionality incorporated, so there is no need to call any extra scripts.
