### ISSUE TITLE
flat 3D effect 

### ISSUE THREAD

**Issue by electech6** [facebook/Surround360#192]
Hi, I have created a 3D image with my device based on the surround360 design. However, when I watch the 3D image in a VR device, I find the 3D effect is quite flat even the person is near the camera. 
It did not improve when I changed the different value of  "Flag_Zero_Parallax_dist". 
I think it should be related with the following code:
![2017-03-28_193406](https://cloud.githubusercontent.com/assets/10663483/24402995/99d6631a-13ed-11e7-8642-1eb09f833519.png)
Could you give me some suggestions to improve the 3D effect? Many thanks!

**Comment by fbriggs** [comment]
please post an example of your results. also, it helps if you can show the exact command you ran, or a screenshot of the GUI specifying options.

what OS are you using? we saw a bug before where stereo came out as mono on linux, but that should be fixed now.

**Comment by electech6** [comment]
I work on Windows OS. See the following options:
![2017-03-30_142912](https://cloud.githubusercontent.com/assets/10663483/24490466/4aac9034-1555-11e7-8bd9-f6aae00d89e7.png)
This is an example of my result:
![test](https://cloud.githubusercontent.com/assets/10663483/24491142/74b2b9f0-1558-11e7-84d0-74d09ea82eb9.jpg)
Is there something wrong with my options? Could you give me some advice to improve the 3D effect?Thanks!
