### ISSUE TITLE
Steps to generate content and view directly in VR headset

### ISSUE THREAD

**Issue by Siddartha123** [facebook/Surround360#199]
Dear Facebook community,
I would like to know the steps to generate the content (either image or video) which can be viewed in any Virtual reality headset with the help of the provided source code and the same data base of Fine arts

My requirement is 
(1) run the source code of particular Facebook surround 360 module
(2) generate the image or video as output
(3) directly use this image or video output and view in any Virtual Reality headset

And for viewing in VR headset, does the image or video need any player kind of thing or can I directly push image in some folder of smart phone, open it and view in VR headset?

I have compiled render module and able to run TestRenderStereoPanorama.
I am able to get left and right eye equi-rectangular images in up/down manner in one image file as shown below:

![eqr_000000_pixflow_low](https://cloud.githubusercontent.com/assets/22633733/24799005/a533e8c4-1bb6-11e7-8224-8fc554bf25a8.png)

and also spherical projection of left and right eye views separately in two image files as shown below:

![sphericalimgl](https://cloud.githubusercontent.com/assets/22633733/24799044/d6036c5e-1bb6-11e7-824b-031c987b8dcf.png)
![sphericalimgr](https://cloud.githubusercontent.com/assets/22633733/24799046/d80dd610-1bb6-11e7-8533-eb770f85626f.png)

I want to view them in VR headset. What additional steps I should follow?
If I use any app from play store, it generates left eye and right eye views and also planar/spherical projections. But we already have those views. I pushed above images in smart phone, opened from gallery and connected VR headset. But the experience is not that good when compared to VR content which Youtube supports.

**Comment by aparrapo** [comment]
Hi @Siddartha123. The equirectangular or cubemap images generated by the Surround360 software can be displayed on GearVR by just dropping the files under the Oculus/360Photos directory on any supported Android phones.

Different VR platforms may require different naming conventions or formats, but that depends on them. Sometimes they may require metadata to be injected on the images/videos, so they can be interpreted as 360/3D. But again, this should be specified by each platform.
