### ISSUE TITLE
Ideal environment for geometric calibration

### ISSUE THREAD

**Issue by akc2267** [facebook/Surround360#205]
When I run the render step with my self generated camera_rig.json, I get pretty decent results. However, when I run geometric calibration to improve the results, the returned camera_rig.json is way off. My initial RMSE value was 927, but at the end of the geometric calibration, the RMSE value was 1100. I took the calibration photos in a library with lots of book shelves and desks and a gridded ceiling light pattern.

What would be the ideal environment for geometric calibration? And has the geometric calibration been tested on side cameras that are over 180deg fisheyes?

**Comment by fbriggs** [comment]
If everything is working as expected, you should get median reprojection error < 1 pixel

A library is a pretty good environment. Ideally, somewhere with lots of "features" (corners), all over the scene. Large blank areas are not good (i.e. outdoor sky). It is also good to have objects at a variety of different distances from the camera.

Yes, geometric calibration has been tested with cameras > 180 deg (i.e. we have gotten good results with 220).
