### ISSUE TITLE
Warning: MODE_7 not supported. Falling back to MODE_0

### ISSUE THREAD

**Issue by mtvv** [facebook/Surround360#206]
I always get this message, when I start CameraControlUI, what does it mean?

**Comment by aparrapo** [comment]
Hi @mtvv , some camera models support MODE_7. According to the Point Grey user manuals:

> Mode 7
> In mode 7 the camera is optimized for high well depth, SNR, and quantum efficiency at the expense of frame rate.
> CCD models implement single tap readout and extended shutter mode.
> The GS3-U3-23S6 and GS3-U3-32S4 and GS3-U3-51S5 and GS3-U3-89S6 and GS3-U3-123S6 models support a 12-bit ADC in mode 7. For these models, all other video modes support a 10-bit ADC.
> For the GS3-U3-28S5 models, this mode is a single-tap mode that lowers frame rate. Imaging performance is not improved.

If we cannot find mode 7, we fallback to mode 0, which should still support 12-bit ADC.
