### ISSUE TITLE
2D panorama stitch with 6 GoPro4

### ISSUE THREAD

**Issue by lvzg2005** [facebook/Surround360#212]
We want to stitch 2D panorama, and we have 6 GoPro4, one for top, the others for side. The largest FOV of this camera is 120 degree. Could you please post the necessary changes to make. I have read your answer for #11, but have no idea about to change 3D to 2D stitch.

**Comment by fbriggs** [comment]
To get 2D, you set the IPD to 0. This can be done by changing one line of code, in this file:
https://github.com/facebook/Surround360/blob/master/surround360_render/scripts/batch_process_video.py

line 51:
--interpupilary_dist 6.4

change to:
--interpupilary_dist 0.0
