### ISSUE TITLE
Is It Possible to 'Unpack'(only for RGB images from RAW) without color calibration data ?

### ISSUE THREAD

**Issue by nukbridge** [facebook/Surround360#213]
Is there any way to get RGB images from RAW binary data without color calibration data(<serial number>.json) ? or can I use some default values ?

I need to get RGB data without color correction or some modification from each camera,

Thanks,

**Comment by aparrapo** [comment]
Hi @nukbridge , the unpacker looks for <serial_number>.json under render/config/isp. You can copy 

https://github.com/facebook/Surround360/blob/master/surround360_render/res/config/camera_rig.json

rename it and copy it for each camera.

Thank you,
