### ISSUE TITLE
Not able to link Halide library in surround360_render

### ISSUE THREAD

**Issue by codestamp** [facebook/Surround360#221]
I am trying to run "make" in the surreound360_render root, but getting errors related to undefined reference to various Halide functions. Upon googling I came to know that the latest Halide commit has this issue and thus an old commit shall be applicable. Thus I decided to use use the Halide git sha c7375fa30f22c509d9e440e42dcae87a5f13f2f7. But still the issue related to Halide is there. I am copying the entire make error under. It seems the error is related to  **"Linking CXX executable bin/CameraIspGen"**

[  3%] Built target LibJSON
[ 29%] Built target LibVrCamera
[ 32%] Built target TestOpticalFlow
[ 35%] Built target TestRenderStereoPanorama
[ 38%] Built target TestImageWarper
[ 41%] Built target TestVignettingDataAcquisition
[ 43%] Linking CXX executable bin/CameraIspGen
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::operator%(Halide::Expr const&, int) [clone .constprop.141]':
CameraIspGen.cpp:(.text+0xd07): undefined reference to `Halide::Internal::Mod::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::cast(Halide::Type, Halide::Expr const&)':
CameraIspGen.cpp:(.text._ZN6Halide4castENS_4TypeERKNS_4ExprE[_ZN6Halide4castENS_4TypeERKNS_4ExprE]+0x319): undefined reference to `Halide::Internal::Cast::make(Halide::Type, Halide::Expr const&)'
CameraIspGen.cpp:(.text._ZN6Halide4castENS_4TypeERKNS_4ExprE[_ZN6Halide4castENS_4TypeERKNS_4ExprE]+0x3b0): undefined reference to `Halide::Internal::Broadcast::make(Halide::Expr const&, int)'
CameraIspGen.cpp:(.text._ZN6Halide4castENS_4TypeERKNS_4ExprE[_ZN6Halide4castENS_4TypeERKNS_4ExprE]+0x404): undefined reference to `Halide::Internal::Broadcast::make(Halide::Expr const&, int)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::operator+(Halide::Expr, Halide::Expr)':
CameraIspGen.cpp:(.text._ZN6HalideplENS_4ExprES0_[_ZN6HalideplENS_4ExprES0_]+0x48): undefined reference to `Halide::Internal::Add::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::operator+(Halide::Expr const&, int)':
CameraIspGen.cpp:(.text._ZN6HalideplERKNS_4ExprEi[_ZN6HalideplERKNS_4ExprEi]+0xa8): undefined reference to `Halide::Internal::Add::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::operator-(Halide::Expr, Halide::Expr)':
CameraIspGen.cpp:(.text._ZN6HalidemiENS_4ExprES0_[_ZN6HalidemiENS_4ExprES0_]+0x48): undefined reference to `Halide::Internal::Sub::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::operator-(Halide::Expr const&, int)':
CameraIspGen.cpp:(.text._ZN6HalidemiERKNS_4ExprEi[_ZN6HalidemiERKNS_4ExprEi]+0xa8): undefined reference to `Halide::Internal::Sub::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::operator*(Halide::Expr, Halide::Expr)':
CameraIspGen.cpp:(.text._ZN6HalidemlENS_4ExprES0_[_ZN6HalidemlENS_4ExprES0_]+0x48): undefined reference to `Halide::Internal::Mul::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::operator*=(Halide::Expr&, Halide::Expr const&)':
CameraIspGen.cpp:(.text._ZN6HalidemLERNS_4ExprERKS0_[_ZN6HalidemLERNS_4ExprERKS0_]+0x7f): undefined reference to `Halide::Internal::Mul::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::operator/(Halide::Expr, Halide::Expr)':
CameraIspGen.cpp:(.text._ZN6HalidedvENS_4ExprES0_[_ZN6HalidedvENS_4ExprES0_]+0x48): undefined reference to `Halide::Internal::Div::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::operator==(Halide::Expr const&, int)':
CameraIspGen.cpp:(.text._ZN6HalideeqERKNS_4ExprEi[_ZN6HalideeqERKNS_4ExprEi]+0xa8): undefined reference to `Halide::Internal::EQ::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::clamp(Halide::Expr const&, Halide::Expr const&, Halide::Expr const&)':
CameraIspGen.cpp:(.text._ZN6Halide5clampERKNS_4ExprES2_S2_[_ZN6Halide5clampERKNS_4ExprES2_S2_]+0x85): undefined reference to `Halide::Internal::lossless_cast(Halide::Type, Halide::Expr const&)'
CameraIspGen.cpp:(.text._ZN6Halide5clampERKNS_4ExprES2_S2_[_ZN6Halide5clampERKNS_4ExprES2_S2_]+0xd0): undefined reference to `Halide::Internal::lossless_cast(Halide::Type, Halide::Expr const&)'
CameraIspGen.cpp:(.text._ZN6Halide5clampERKNS_4ExprES2_S2_[_ZN6Halide5clampERKNS_4ExprES2_S2_]+0xee): undefined reference to `Halide::Internal::Min::make(Halide::Expr const&, Halide::Expr const&)'
CameraIspGen.cpp:(.text._ZN6Halide5clampERKNS_4ExprES2_S2_[_ZN6Halide5clampERKNS_4ExprES2_S2_]+0xfe): undefined reference to `Halide::Internal::Max::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::select(Halide::Expr, Halide::Expr, Halide::Expr)':
CameraIspGen.cpp:(.text._ZN6Halide6selectENS_4ExprES0_S0_[_ZN6Halide6selectENS_4ExprES0_S0_]+0x3ad): undefined reference to `Halide::Internal::Select::make(Halide::Expr const&, Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::pow(Halide::Expr, Halide::Expr)':
CameraIspGen.cpp:(.text._ZN6Halide3powENS_4ExprES0_[_ZN6Halide3powENS_4ExprES0_]+0x5f): undefined reference to `Halide::Internal::raise_to_integer_power(Halide::Expr const&, long)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::Param<int>::Param()':
CameraIspGen.cpp:(.text._ZN6Halide5ParamIiEC2Ev[_ZN6Halide5ParamIiEC5Ev]+0x67): undefined reference to `Halide::Internal::Parameter::Parameter(Halide::Type, bool, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::Param<bool>::Param()':
CameraIspGen.cpp:(.text._ZN6Halide5ParamIbEC2Ev[_ZN6Halide5ParamIbEC5Ev]+0x67): undefined reference to `Halide::Internal::Parameter::Parameter(Halide::Type, bool, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `Halide::Param<float>::Param(char const*)':
CameraIspGen.cpp:(.text._ZN6Halide5ParamIfEC2EPKc[_ZN6Halide5ParamIfEC5EPKc]+0x68): undefined reference to `Halide::Internal::Parameter::Parameter(Halide::Type, bool, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `CameraIspGen<true>::greenBluePixel()':
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb1EE14greenBluePixelEv[_ZN12CameraIspGenILb1EE14greenBluePixelEv]+0x9f): undefined reference to `Halide::Internal::And::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `CameraIspGen<true>::bluePixel()':
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb1EE9bluePixelEv[_ZN12CameraIspGenILb1EE9bluePixelEv]+0xa2): undefined reference to `Halide::Internal::And::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `CameraIspGen<true>::redPixel()':
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb1EE8redPixelEv[_ZN12CameraIspGenILb1EE8redPixelEv]+0xa2): undefined reference to `Halide::Internal::And::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `CameraIspGen<true>::greenRedPixel()':
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb1EE13greenRedPixelEv[_ZN12CameraIspGenILb1EE13greenRedPixelEv]+0xa5): undefined reference to `Halide::Internal::And::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `CameraIspGen<true>::deinterleave(Halide::Func)':
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb1EE12deinterleaveEN6Halide4FuncE[_ZN12CameraIspGenILb1EE12deinterleaveEN6Halide4FuncE]+0x133): undefined reference to `Halide::Internal::And::make(Halide::Expr const&, Halide::Expr const&)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o:CameraIspGen.cpp:(.text._ZN12CameraIspGenILb1EE12deinterleaveEN6Halide4FuncE[_ZN12CameraIspGenILb1EE12deinterleaveEN6Halide4FuncE]+0x1f3): more undefined references to `Halide::Internal::And::make(Halide::Expr const&, Halide::Expr const&)' follow
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `CameraIspGen<true>::demosaic(Halide::Func, Halide::Func, Halide::Func, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Expr)':
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb1EE8demosaicEN6Halide4FuncES2_S2_NS1_4ExprES3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_[_ZN12CameraIspGenILb1EE8demosaicEN6Halide4FuncES2_S2_NS1_4ExprES3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_]+0x1425): undefined reference to `Halide::Func::vectorize(Halide::VarOrRVar, int, Halide::TailStrategy)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `CameraIspGen<true>::generate(Halide::Target, Halide::Func, Halide::Param<int>, Halide::Param<int>, Halide::Func, Halide::Func, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::ImageParam, Halide::ImageParam, Halide::Param<bool>, int)':
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb1EE8generateEN6Halide6TargetENS1_4FuncENS1_5ParamIiEES5_S3_S3_NS4_IfEES6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_NS1_10ImageParamES7_NS4_IbEEi[_ZN12CameraIspGenILb1EE8generateEN6Halide6TargetENS1_4FuncENS1_5ParamIiEES5_S3_S3_NS4_IfEES6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_NS1_10ImageParamES7_NS4_IbEEi]+0x8e2): undefined reference to `Halide::Internal::Sub::make(Halide::Expr const&, Halide::Expr const&)'
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb1EE8generateEN6Halide6TargetENS1_4FuncENS1_5ParamIiEES5_S3_S3_NS4_IfEES6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_NS1_10ImageParamES7_NS4_IbEEi[_ZN12CameraIspGenILb1EE8generateEN6Halide6TargetENS1_4FuncENS1_5ParamIiEES5_S3_S3_NS4_IfEES6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_NS1_10ImageParamES7_NS4_IbEEi]+0xcd2): undefined reference to `Halide::Func::vectorize(Halide::VarOrRVar, int, Halide::TailStrategy)'
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb1EE8generateEN6Halide6TargetENS1_4FuncENS1_5ParamIiEES5_S3_S3_NS4_IfEES6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_NS1_10ImageParamES7_NS4_IbEEi[_ZN12CameraIspGenILb1EE8generateEN6Halide6TargetENS1_4FuncENS1_5ParamIiEES5_S3_S3_NS4_IfEES6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_NS1_10ImageParamES7_NS4_IbEEi]+0xf8e): undefined reference to `Halide::Func::vectorize(Halide::VarOrRVar, int, Halide::TailStrategy)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `CameraIspGen<false>::edgeAwareDemosaic(Halide::Func, Halide::Func, Halide::Func, Halide::Func, Halide::Func&, Halide::Func&, Halide::Func&, Halide::Func&, Halide::Func&, Halide::Func&, Halide::Func&, Halide::Func&, Halide::Func&, Halide::Func&, Halide::Func&, Halide::Func&, Halide::Func&)':
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_[_ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_]+0x3044): undefined reference to `Halide::Internal::LE::make(Halide::Expr const&, Halide::Expr const&)'
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_[_ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_]+0x32d5): undefined reference to `Halide::Internal::LT::make(Halide::Expr const&, Halide::Expr const&)'
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_[_ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_]+0x5abb): undefined reference to `Halide::Func::vectorize(Halide::VarOrRVar, int, Halide::TailStrategy)'
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_[_ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_]+0x5cb4): undefined reference to `Halide::Func::vectorize(Halide::VarOrRVar, int, Halide::TailStrategy)'
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_[_ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_]+0x5ead): undefined reference to `Halide::Func::vectorize(Halide::VarOrRVar, int, Halide::TailStrategy)'
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_[_ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_]+0x60a6): undefined reference to `Halide::Func::vectorize(Halide::VarOrRVar, int, Halide::TailStrategy)'
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_[_ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_]+0x629f): undefined reference to `Halide::Func::vectorize(Halide::VarOrRVar, int, Halide::TailStrategy)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o:CameraIspGen.cpp:(.text._ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_[_ZN12CameraIspGenILb0EE17edgeAwareDemosaicEN6Halide4FuncES2_S2_S2_RS2_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_S3_]+0x6498): more undefined references to `Halide::Func::vectorize(Halide::VarOrRVar, int, Halide::TailStrategy)' follow
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `CameraIspGen<false>::applyUnsharpMask(Halide::Func, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Param<float>, Halide::Param<bool>, int)':
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb0EE16applyUnsharpMaskEN6Halide4FuncENS1_4ExprES3_S3_S3_S3_S3_NS1_5ParamIfEENS4_IbEEi[_ZN12CameraIspGenILb0EE16applyUnsharpMaskEN6Halide4FuncENS1_4ExprES3_S3_S3_S3_S3_NS1_5ParamIfEENS4_IbEEi]+0x57e): undefined reference to `Halide::Internal::Sub::make(Halide::Expr const&, Halide::Expr const&)'
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb0EE16applyUnsharpMaskEN6Halide4FuncENS1_4ExprES3_S3_S3_S3_S3_NS1_5ParamIfEENS4_IbEEi[_ZN12CameraIspGenILb0EE16applyUnsharpMaskEN6Halide4FuncENS1_4ExprES3_S3_S3_S3_S3_NS1_5ParamIfEENS4_IbEEi]+0x7b4): undefined reference to `Halide::Internal::Sub::make(Halide::Expr const&, Halide::Expr const&)'
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb0EE16applyUnsharpMaskEN6Halide4FuncENS1_4ExprES3_S3_S3_S3_S3_NS1_5ParamIfEENS4_IbEEi[_ZN12CameraIspGenILb0EE16applyUnsharpMaskEN6Halide4FuncENS1_4ExprES3_S3_S3_S3_S3_NS1_5ParamIfEENS4_IbEEi]+0xd87): undefined reference to `Halide::Func::vectorize(Halide::VarOrRVar, int, Halide::TailStrategy)'
CMakeFiles/CameraIspGen.dir/source/camera_isp/CameraIspGen.cpp.o: In function `CameraIspGen<false>::generate(Halide::Target, Halide::Func, Halide::Param<int>, Halide::Param<int>, Halide::Func, Halide::Func, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::Param<float>, Halide::ImageParam, Halide::ImageParam, Halide::Param<bool>, int)':
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb0EE8generateEN6Halide6TargetENS1_4FuncENS1_5ParamIiEES5_S3_S3_NS4_IfEES6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_NS1_10ImageParamES7_NS4_IbEEi[_ZN12CameraIspGenILb0EE8generateEN6Halide6TargetENS1_4FuncENS1_5ParamIiEES5_S3_S3_NS4_IfEES6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_NS1_10ImageParamES7_NS4_IbEEi]+0xd9d): undefined reference to `Halide::Func::vectorize(Halide::VarOrRVar, int, Halide::TailStrategy)'
CameraIspGen.cpp:(.text._ZN12CameraIspGenILb0EE8generateEN6Halide6TargetENS1_4FuncENS1_5ParamIiEES5_S3_S3_NS4_IfEES6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_NS1_10ImageParamES7_NS4_IbEEi[_ZN12CameraIspGenILb0EE8generateEN6Halide6TargetENS1_4FuncENS1_5ParamIiEES5_S3_S3_NS4_IfEES6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_S6_NS1_10ImageParamES7_NS4_IbEEi]+0x1055): undefined reference to `Halide::Func::vectorize(Halide::VarOrRVar, int, Halide::TailStrategy)'
collect2: error: ld returned 1 exit status
CMakeFiles/CameraIspGen.dir/build.make:94: recipe for target 'bin/CameraIspGen' failed
make[2]: *** [bin/CameraIspGen] Error 1
CMakeFiles/Makefile2:297: recipe for target 'CMakeFiles/CameraIspGen.dir/all' failed
make[1]: *** [CMakeFiles/CameraIspGen.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Max-R7** [comment]
Did you use the newest version of halide? If so, please download a version prior 15th March 2017. If this still does not work, we are using a December 2016 version of halide and this defiantly compiles without error.

**Comment by codestamp** [comment]
Thanks, I went for the Halide commit (b8bfea4226fb6c12da71cff6fda954dbaad82589) dated 15 March 2017. Somehow still had errors with make but successfully compiled with the alternative cmake option.
