### ISSUE TITLE
Question about the tools for calibration ?

### ISSUE THREAD

**Issue by jiangjingping** [facebook/Surround360#224]
when doing calibration，we use : 
- a color checker 
- a gray chart ,
- a SpyderCUBE
is that all we need ?
and  what about the size of the color checker and the gray chart?
thank u :)

**Comment by aparrapo** [comment]
Hi @jiangjingping, yes, this is all you need. For vignetting calibration we also use a two-axis rotating device to uniformly cover the entire camera frame, but it can be done by hand.

These are ones we use:

- Color Checker: http://xritephoto.com/colorchecker-classic
- Gray chart: http://xritephoto.com/ph_product_overview.aspx?id=943&catid=28
- SpyderCUBE: http://www.datacolor.com/photography-design/product-overview/spydercube/

**Comment by jiangjingping** [comment]
@aparrapo okay, got it , thank u~
