### ISSUE TITLE
Error installing gflags (method 1 - Linux only):

### ISSUE THREAD

**Issue by VRabbitHole** [facebook/Surround360#23]
vrlf@vrlf:/media/sandshare$ sudo apt-get install libgflags2 libgflags-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libgflags2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libgflags2v5:i386 libgflags2v5

E: Package 'libgflags2' has no installation candidate

I'm installing on Ubuntu 16.04 LTS .... on BTRFS share.

**Comment by aparrapo** [comment]
We have not tested the installation on Ubuntu 16.04 LTS yet, so I'm guessing the gflags package has changed.

I assume `libgflags2v5` would work as well.

Else, check the possible options via

`apt-cache search gflags`

Let me know if that doesn't work and I'll be more than happy to help :)

**Comment by VRabbitHole** [comment]
I tried libgflags2v5 but Installer couldn't find package.

**Comment by VRabbitHole** [comment]
Issue fixed -thanks.

**Comment by aparrapo** [comment]
How did you fix it? Did you find another available package?

**Comment by VRabbitHole** [comment]
Updated everything I could .... went through the whole install process again .... inserted libgflags2v5 this time around and install worked just fine ... I did do a reboot of the PC before starting second install ... not sure what exactly fixed the problem but all is good now.

Might be useful to compile a fresh install version for Ubuntu 16.04 LTS ... it's been out a while now and is pretty stable and has latest version of BTRFS and ZFS included plus all the other latest packages. I know you guys recommend the Areca 8 x bay RAID and hardware RAID card for the RAW storage device but SDS (Software Defined Storage) with SSDs and nvme is the way to go for fast flash storage ... lighter, faster, cheaper and with Brtfs and ZFS better data integrity ... I've set up a 16 x SSD pool in half the space/weight required by the Areca 8 x bay chassis .... just a thought. I used eight Areca RAIDS on a WB movie a couple of years ago ... very reliable for sure but heavy as hell ... try lugging eight of those around the US/Canada and watch your biceps increase in size :-)

**Comment by aparrapo** [comment]
Thanks for the advice! We are looking at other storage systems as well. And yes, we've been getting some workouts with the Areca boxes :)

**Comment by VRabbitHole** [comment]
Be very interested in your thoughts on SDS storage architectures with SSDs and NVMe ... it's evolving rapidly ... please keep us in the loop on developments .... I'm presenting a short talk at the Flash Memory Summit next month in Santa Clara on 'Flash Enhanced Storage for 4K and VR Workflows' ... plus, lots of interest in VR in LA at the moment.
