### ISSUE TITLE
Why should the panoramas resized to FINAL_EQR_WIDTH x FINAL_EQR_HEIGHT?

### ISSUE THREAD

**Issue by kevinra** [facebook/Surround360#235]
I'm wondering why can't we have

FINAL_EQR_WIDTH == EQR_WIDTH
FINAL_EQR_HEIGHT == FINAL_EQR_HEIGHT

so that resizing at the end can be avoided. Their resolution is not very different after all. Only reason I can think of is that FINAL_EQR_WIDTH might not be divisible by camera numbers.

**Comment by aparrapo** [comment]
Hi @kevinra, yes, it's to make sure it's divisible by the number of cameras :)
