### ISSUE TITLE
Halide.h is missing

### ISSUE THREAD

**Issue by SuTanTank** [facebook/Surround360#240]
I never used Halide before, but when I tried to follow the instructions, I found out that I need that "unpacker" program to process the binary files.  And then I found out that to build the unpacker, I need to install halide. And after I did as the guide did and try to build the unpacker program, it failed and told me Halide.h is missing. 

The halide.h doesn't exist in the entire halide repository and indeed, the tutorials cpp files provided by Halide include this Halide.h file, which makes me really confused. 

So where is this Halide.h file? Has it changed to another filename?

**Comment by SuTanTank** [comment]
There is one command "make -j8" missing in the section of installing Halide. Halide.h is inside cmake_build/include after building.

**Comment by aparrapo** [comment]
This issue is the same as #238 :)
