### ISSUE TITLE
Error when Linking the executable for CameraControlUI

### ISSUE THREAD

**Issue by Tangelo1** [facebook/Surround360#246]
Any ideas what could be causing this? I uninstalled and reinstalled openCV and that didnt seem to help
![screenshot from 2017-11-09 10-30-23](https://user-images.githubusercontent.com/9088470/32613654-7d38f634-c539-11e7-8d62-03fc1725714d.png)

**Comment by aziz221** [comment]
تم الإرسال من جهاز Samsung


-------- الرسالة الأصلية --------
من: Tyler Angelo <notifications@github.com>
التاريخ: ٠٩‏/١١‏/٢٠١٧ ٦:٣٤ م (GMT+03:00)
إلى: facebook/Surround360 <Surround360@noreply.github.com>
نسخة: Subscribed <subscribed@noreply.github.com>
الموضوع: [facebook/Surround360] Error when Linking the executable for CameraControlUI (#246)


Any ideas what could be causing this? I uninstalled and reinstalled openCV and that didnt seem to help
[screenshot from 2017-11-09 10-30-23]<https://user-images.githubusercontent.com/9088470/32613654-7d38f634-c539-11e7-8d62-03fc1725714d.png>

**Comment by aparrapo** [comment]
Hi @Tangelo1. How did you install opencv? It seems ${OpenCV_LIBS} cannot find the libraries.

**Comment by Tangelo1** [comment]
Well I originally built it manually, then I decided to use this script https://github.com/milq/milq/blob/master/scripts/bash/install-opencv.sh
