### ISSUE TITLE
what's "grayscale chart "?

### ISSUE THREAD

**Issue by sdlcwangsong** [facebook/Surround360#261]
I saw this word in readme [https://github.com/facebook/Surround360/blob/master/surround360_render/CALIBRATION.md](https://github.com/facebook/Surround360/blob/master/surround360_render/CALIBRATION.md) 

"a uniform and constant illuminant, place the **grayscale chart** in front of a camera and take as many pictures as desired (recommended more than 20) "

where can I get it?
who can help me?

**Comment by aparrapo** [comment]
Hi @sdlcwangsong, we use one like this for our calibration:
http://xritephoto.com/colorchecker-18-gray-balance

If you want to use a different chart, make sure it's not glossy, i.e. it reflects incoming light uniformly.
