### ISSUE TITLE
Custom illuminants other than d65

### ISSUE THREAD

**Issue by mtvv** [facebook/Surround360#266]
Is it possible to perform color calibration using illuminants with a different color temp?
I am having problems finding a D65 compatible LED light, but there seems to be plenty of options in the 4000K-5600K range.

**Comment by aparrapo** [comment]
Hi @mtvv, we support D65 and D50, but you can use a different illuminant if you have its ground truth values and you add them to the list in https://github.com/facebook/Surround360/blob/390d046a09b50a6948113750a8103436e2bf31fd/surround360_render/source/calibration/ColorCalibration.h#L42
