### ISSUE TITLE
x24 camera?

### ISSUE THREAD

**Issue by fustkilas** [facebook/Surround360#268]
Hello, this is perhaps not the right venue for this question, apologies if so.

I am trying to reach someone who can give me access to the x24 camera for a day, as part of an art installation in New York City. Would you know how/who I can approach about this?

**Comment by aparrapo** [comment]
Hi @fustkilas. Apologies for the late reply. The x24 was a prototype camera and we decided to move on to the new Manifold in a partnership with RED Digital Cinema:
https://facebook360.fb.com/2018/09/26/film-the-future-with-red-and-facebook-360/

You can find the new open sourced code here:
https://github.com/facebook/facebook360_dep
