### ISSUE TITLE
Stereoscopic coverage

### ISSUE THREAD

**Issue by BroadDong** [facebook/Surround360#27]
Could you  minutely explain why the stereoscopic coverage is the Centerline +/- 144(h),77(v) degrees?
Especially the horizontal view is +/- 144?

**Comment by fbriggs** [comment]
The vertical field of the view of the side cameras is 90 degrees. After correcting for barrel distortion, that decreases to 77. The side cameras are the only ones that give stereo. There is nothing in the system that is 144.
