### ISSUE TITLE
Optimum file system for ingest and render engine?

### ISSUE THREAD

**Issue by VRabbitHole** [facebook/Surround360#29]
Did you guys benchmark the different File Systems available on Ubuntu for the Ingest/Render machine? Any specific recommendations? ... eg, EXT4 v. XFS v. ZFS v. BTRFS.

Thanks.

**Comment by aparrapo** [comment]
@VRabbitHole sorry for the late reply. We have not explicitly benchmarked Linux filesystems, but we've tried some and we decided to go with EXT4. It is better known and used in the production environment and it fits all of our needs (allow large files, well-developed fsck, cross-os compatibility). We had some reliability issues with XFS. I do not remember trying BTRFS.
