### ISSUE TITLE
Is there a manual for run_all.py

### ISSUE THREAD

**Issue by dzyong** [facebook/Surround360#31]
I built the stacked.png, top_vis.png, bottom_vis.png, bottom2_vis.png and rectify_my_rig.yml for https://s3-us-west-2.amazonaws.com/surround360/sample/sample_dataset.zip by following the CALIBRATION.md's instructions.

Then how to process the next step and how to use run_all.py.
Would you please give an example for using run_all.py which is like CALIBRATION.md?

Thanks

**Comment by fbriggs** [comment]
If you execute run_all.py with --help, it will print a list of all arguments and a short description of what they do.

There are more detailed (illustrated) instructions here.. sorry for the non-obvious location:
https://github.com/facebook/Surround360/blob/master/surround360_design/assembly_guide/Surround360_Manual.pdf 

If you have further questions, please open a new issue.
