### ISSUE TITLE
numNovelViews large than lazyNoveViewBuffer size lead to crash

### ISSUE THREAD

**Issue by tpys** [facebook/Surround360#33]
Hello,

When run TestRenderStereoPanorama program crash, Because two variable conflict, numNovelViews(around 683 ) large than FLAGS_eqr_width / numCams(around 18).

In function a:
void generateRingOfNovelViewsAndRenderStereoSpherical() {
    const int numNovelViews = camImageWidth - overlapImageWidth; // per image pair
}

in function b:
void renderStereoPanoramaChunksThread(
     LazyNovelViewBuffer lazyNovelViewBuffer(FLAGS_eqr_width / numCams, camImageHeight);
}

so how to set these two variables? what are relations between them? thanks a lot!!!!

**Comment by fbriggs** [comment]
In order to help, please provide the following:
- list any commands you are running
- provide any config files you have changed
- provide the dataset (images) you are using
