### ISSUE TITLE
Sample data download link could be from CloudFront instead of directly from S3

### ISSUE THREAD

**Issue by jasjuang** [facebook/Surround360#35]
Could change this link https://s3-us-west-2.amazonaws.com/surround360/sample/sample_dataset.zip  into Amazon CloudFront that utilizes CDN instead of directly from S3 so the download speed could be faster if I am not in the US.

**Comment by fbriggs** [comment]
try this one:
http://surround360.hacktv.xyz/sample/sample_dataset.zip
