### ISSUE TITLE
Streaming Solution

### ISSUE THREAD

**Issue by manfranz** [facebook/Surround360#37]
Hi,
thanks for your job. We're going to assembly the Surround and we'd like to create our custom player for 8k VR video.   Do you provide any software solution that takes advantage of your dynamic streaming algorithm and pyramid map? Otherwise can we customize FB/Oculus player? The player should be embedded into an Oculus/Gear VR app where we'll provide (our) 8k video VR experience downloadable or in streaming.
Thanks,
Francesco

**Comment by bkcabral** [comment]
Currently we do not have a public API for dynamic streaming. I will pass along this interest to the apropos development team.
