### ISSUE TITLE
Facing error while compiling render on Mac 

### ISSUE THREAD

**Issue by Ahmad-Masood** [facebook/Surround360#41]
When i execute following part:

cd /surround360/surround360_render
cmake -DCMAKE_BUILD_TYPE=Release
make

I run into following error:

ld: library not found for -lgflags
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/TestRenderWithoutSides] Error 1
make[1]: *** [CMakeFiles/TestRenderWithoutSides.dir/all] Error 2
make: *** [all] Error 2

Any help regarding this issue?

**Comment by ssaroha** [comment]
For anybody else facing this issue, fix is to ensure that CMakeLists.txt knows where to find the linked libraries (usually brew installed libs like gflags are in /usr/local/lib). 
One way to achieve that is by adding the following to CMakeLists.txt.

LINK_DIRECTORIES(/usr/local/lib)
