### ISSUE TITLE
Intermediate results for optical flow testing

### ISSUE THREAD

**Issue by mimiaofandisp** [facebook/Surround360#42]
Hi, I wonder if you could also provide the intermediate results generated from optical flow, cause I got some really weird novel view results. Are these what I supposed to get?
![000000](https://cloud.githubusercontent.com/assets/4665386/17528993/79e823fe-5e26-11e6-8574-39b1b0400a1f.png)
![000001](https://cloud.githubusercontent.com/assets/4665386/17528998/79efc460-5e26-11e6-9056-322fc7a56763.png)
![000002](https://cloud.githubusercontent.com/assets/4665386/17528994/79e92bc8-5e26-11e6-88ad-ab7dbc7d5e8e.png)
![000003](https://cloud.githubusercontent.com/assets/4665386/17528996/79eda720-5e26-11e6-9656-1090dad66112.png)
![000004](https://cloud.githubusercontent.com/assets/4665386/17528995/79ec2026-5e26-11e6-97f1-ad005f7672b0.png)
![000005](https://cloud.githubusercontent.com/assets/4665386/17528997/79edcd04-5e26-11e6-9ec6-146d38a3722c.png)
![000006](https://cloud.githubusercontent.com/assets/4665386/17528999/79fa8e68-5e26-11e6-9651-124a1c39e99e.png)
![000007](https://cloud.githubusercontent.com/assets/4665386/17529002/7a038bda-5e26-11e6-9232-b9f10f22bb99.png)
![000008](https://cloud.githubusercontent.com/assets/4665386/17529000/7a01d42a-5e26-11e6-8f93-1ff0ae7433e5.png)
![000009](https://cloud.githubusercontent.com/assets/4665386/17529003/7a05132e-5e26-11e6-8365-08844fa861b4.png)
![000010](https://cloud.githubusercontent.com/assets/4665386/17529001/7a030746-5e26-11e6-9346-ef9d5fb44e1c.png)

**Comment by fbriggs** [comment]
These definitely look messed up. My guess is that you are trying to input projections into flow, but that is actually not what goes into flow (it is the overlap images, found in /flow_images that go into flow). I can't really do much unless you provide complete information about what you are doing, i.e. all commands you are running + anything else you did.

My general recommendation is to use 'python scripts/run_all.py' and make sure your UI configuration exactly matches the screenshot that goes with sample_result.zip.

**Comment by mimiaofandisp** [comment]
OK, that's the reason, I input the projections into flow. 
Yeah, I already used run_all.py and got the exact same result as your sample output.
trying to figure out the algorithm now.
