### ISSUE TITLE
17 x camera simulator?

### ISSUE THREAD

**Issue by VRabbitHole** [facebook/Surround360#50]
Given that the next batch of GreyPoint cameras has slipped to the end of October, is there any way to emulate the input and bandwidth of the 17 x cameras into the 5 x USB cards?

Single sourcing the key component of the FB 360 Surround ecosystem is going to cause problems ... are there any other sources apart from GP direct ... ie, does FB have a stash in a back-room somewhere? ... just kidding .. but seriously wondering how we're going to test the end-to-end pipeline without any RAW files to play with :-(

**Comment by bkcabral** [comment]
We have no stash ;-)   As for single sourcing - one of the things we hope(d) for is that people would in fact try different sources and different cameras.   Granted this is more work.   As for simulating band width - we really didn't need to do that. We just made sure that each component could operate with particular BW specs.   Sure making it work is always a challenge but we really didn't have issues there.
