### ISSUE TITLE
Matthews VRIG?

### ISSUE THREAD

**Issue by VRabbitHole** [facebook/Surround360#54]
Matthews Studio Equipment have been making pro production and grip gear for years and have just come out with the VRIG which is purposely designed for VR cameras:
 
![screen shot 2016-08-13 at 10 09 06 am](https://cloud.githubusercontent.com/assets/8683168/17644611/2856aa70-6140-11e6-83ef-1cf127b8850a.png)

Just wondering if the VRIG would work with 360 Surround and how easy/difficult it would be to attach the 'flying saucer' directly to the VRIG using the Baby Pin rather than the 22 inch Support Tube (FB360_V1_26):

![screen shot 2016-08-13 at 10 20 10 am](https://cloud.githubusercontent.com/assets/8683168/17644625/7322e906-6140-11e6-8403-f5c077842630.png)

.... or is 22 ins Support Tube an integral part of the stereo geometry underneath the camera and for the 'pole removal' module to work correctly?

My thinking is that the VRIG attached directly to the Baby Pin might provide more stability/rigidity for when the 360 Camera is on a dolly, etc.

Also, what's the total weight of the 360 Surround fully loaded including USB cables? ... there's two models available depending on weight of camera rig.

Here's the link to the intro video from [Matthews](http://www.msegrip.com/vrig/) for those who want to know more.

**Comment by andrewcoward** [comment]
Hi,

Thank you for pointing this out, it does look like it may be suitable for the camera.  We ordered one last week and are expecting it to arrive this week.  

We are not sure of the best way to attach the new stand to the camera, and want to look at the stand in person.  If we find it works well, we will post an update (as well as models and drawings of any required adapters).

A tube length of 22" is not integral, but what is important is to keep the diameter of the pole (and cables) reasonably small for as long as possible.  We need to test out the attachment system and cable run with the new stand to see how it works for this camera.

The total weight of the 360 surround including the USB cables is about 40 lbs including the steel shells.  We ordered the 75 lb capacity stand (VRig S75 Kit). 

Thank you for your questions and comments.
