### ISSUE TITLE
Changing cmosis_fujinon.json

### ISSUE THREAD

**Issue by cvaldesmol** [facebook/Surround360#57]
I see that on cmosis_fujinon.json you have all the parameters to do the color correction, remove noise, white balance, etc
If I were to change to different cameras how can I define the right values to put there?
Do you have scripts to calculate those values? how did you find them for the current camaras?

**Comment by fbriggs** [comment]
Currently the values in cmsosi_fujinon.json are tuned manually. However, we are working on an automatic process for obtaining color calibration. Some of that is available now: https://github.com/facebook/Surround360/commit/493191e28489b92cf9d5ce2a7592f0aafcf5ea7a

The main script is surround360_render/scripts/color_calibrate_all.py. I don't think we have full step-by-step documentation for this yet, and this is a relatively new feature in the software, so it is subject to change.

At a high level, the procedure consists of taking pictures of a color calibration chart (Macbeth chart) with each camera under fixed lighting conditions, then running this script to generate the calibration json files.
