### ISSUE TITLE
Camera Control soft

### ISSUE THREAD

**Issue by BroadDong** [facebook/Surround360#62]
![2016-08-18 15 55 55](https://cloud.githubusercontent.com/assets/20699811/17766211/9c14e5b0-655c-11e6-8b86-c08e5b429615.png)
**The error is that there isn't "#include <libavcodec/avcodec.h>". But I have installed 
it. Why?**
![2016-08-18 16 01 45](https://cloud.githubusercontent.com/assets/20699811/17766304/1b5ba16a-655d-11e6-9e98-f561b3358cfa.png)

**Comment by superdog8** [comment]
Please configure ffmpeg with following flags:
 --enable-nonfree --enable-gpl --enable-libx264 --enable-shared --enable-libvpx

**Comment by DxgHandInHand** [comment]
I have installed ffmpeg and configure it as show below:
--enable-nonfree --enable-gpl --enable-libx264 --enable-shared --enable-libvpx
But it failed. Why?
![2016-08-29 16_21_59____________](https://cloud.githubusercontent.com/assets/20218626/18045442/6ab19e94-6e05-11e6-9830-df55572c4f2e.png)

**Comment by DxgHandInHand** [comment]
could you tell me the detail?

**Comment by IsaacZhi** [comment]
You should add the ffmpeg's include path to gcc search path.

**Comment by aparrapo** [comment]
@DxgHandInHand did you solve this issue?

**Comment by aparrapo** [comment]
@DxgHandInHand closing this issue for now. Please feel free to reopen it if you still haven't solved it.
