### ISSUE TITLE
How can I get the gui of the render software?

### ISSUE THREAD

**Issue by DxgHandInHand** [facebook/Surround360#63]
Because I have no experience in Linux development. Could you give the method that how I can get the gui of the render software?

**Comment by fbriggs** [comment]
First you will need to install the software, including the Gooey library, which is a requirement for the GUI.

After that, run the following commands on the terminal:

cd <wherever you put the /surround360_render folder>
python scripts/run_all.py

That launches the GUI :)

**Comment by russellkaye** [comment]
Thanks!
