### ISSUE TITLE
New Rig Geometry File

### ISSUE THREAD

**Issue by knottb** [facebook/Surround360#64]
I'm trying to change the camera configuration to test on my own images. In particular, in the rig geometry file, I am trying to change the top and bottom camera configurations to be non-fisheye cameras, but I don't know what parameters to use so I'm getting a "VrCamException: failed to parse json camera arrray description" error.

**Comment by fbriggs** [comment]
Non-fisheye lenses for the top/bottom cameras are not currently supported by the rendering software. Even if they were, I'm not sure it makes sense. The top lens needs to have enough FOV to cover the hole left over from the side cameras, with some overlap.

If you post more about what specific lenses you are trying to use I might have more comments..

Thanks!
