### ISSUE TITLE
LazyNovelViewBuffer doubt

### ISSUE THREAD

**Issue by angiequi** [facebook/Surround360#65]
I'm reading the code, and I cannot understand the meaning of what you call time shift "t" (the third value in warpL[u][v] = (x, y, t). Can you please solve my doubt?
Also I would like to know what is the variable "vergeAtInfinitySlabDisplacement"?
Thank you

**Comment by fbriggs** [comment]
the value of t ranges between 0 and 1. at 0 it corresponds to one of the images, and 1 corresponds to the other image. values in between represent virtual cameras midway between the two real cameras.

vergeAtInfinitySlabDisplacement is the amount of horizontal translation applied to the left and right eye panoramas to align them such that objects at a distance of infinity have zero parallax.
