### ISSUE TITLE
Explain a little bit about i = r * sin(FOV/2 - 360/n)?

### ISSUE THREAD

**Issue by mimiaofandisp** [facebook/Surround360#69]
cannot quite understand what (FOV/2 - 360/n) means.

**Comment by fbriggs** [comment]
i = r * sin(FOV/2 - 360/n)
r = radius of the rig
FOV = horizontal FOV of side camera lens
n = number of cameras in ring

So r, FOV, and n are properties of the camera array that you can choose when building it. The result 'i' is the how far from the origin we can put a virtual "eye" for the purpose of making a stereo panorama. So if i > 3.2cm, then we can put two eyes 6.4cm apart. That is what is necessary to get full depth in stereo video.
