### ISSUE TITLE
calibration foundCheckerboard

### ISSUE THREAD

**Issue by knottb** [facebook/Surround360#72]
I am trying to calibrate with ./bin/TestIntrinsicCalibration but I am having some trouble. I have tried different checkerboard sizes .jpg .png in both color and black and white, but no matter what I do I  always get foundCheckerboard = 0. When I try calibrating on the test image provided by Facebook, however, I get foundCheckerboard = 1. I am wondering if there is some requirement I am missing for the findChessBoardCorners function to work properly.

Thanks.

**Comment by fbriggs** [comment]
My first suggestion is to check what you are passing in to TestIntrinsicCalibration for --checkerboard_width and --checkerboard_height. If this doesn't match you image, OpenCV won't find the checkerboard. Also note that OpenCV counts the width/height of the checkerboard starting from interior corners, so the value it expects may be 1 less than what the obvious value. Try this and if it doesn't work, please post an example of the images you are using, plus the exact command that you ran. Thanks.
