### ISSUE TITLE
recommended values for r

### ISSUE THREAD

**Issue by EnriqueMVega** [facebook/Surround360#75]
I read here that the increasing the rig radius makes optical flow more difficult. are there any recommended values? for example from 10 to 16 (or something along those lines)?
I guess that also depend on overlap?

**Comment by fbriggs** [comment]
The smaller the better. However, as you make r smaller, you also need either more cameras, or wider FOV. It all comes down to the formula i = r * sin(FOV/2 - 360/n). As long as i > 3.2cm, the design can work in our software. However, given that constraint, you should minimize r, and maximize n for best results.
