### ISSUE TITLE
How to capture single image use CameraControl ?

### ISSUE THREAD

**Issue by IsaacZhi** [facebook/Surround360#77]
I have compiled the CameraControl.
Now I have only one point grey camera for test.

I try cmd line command in surround360_camera_ctl\source\camera_control\README.txt
== Single image with params ==
sudo ./CameraControl --nframes 1 --brightness 13.5 --exposure 0.18 --gamma 2.3 --shutter 10.0 --gain 4.500 --whitebalance "300 500" --numcams 1 --debug

== Single 8-bit RAW image ==
sudo ./CameraControl --nframes 1 --raw --nbits 8 --brightness 10.449 --exposure 2.400 --shutter 100.0 --gain 7.000 --numcams 1 --debug

I modify the --numcams from 17 to 1

I can see two file 0.bin and 1.bin with 0 bytes.

If I add --cli in the command, it will said "Press 'r' to start recording, 's' to stop recording, 'q' to quit." 
When I press r, it will write to 0.bin, after several seconds I stop.
I check the 0.bin 's filesize, it maybe 1G or 2G or more, maybe it wrtie all frames?

How to capture single image use CameraControl with only one camera?

**Comment by superdog8** [comment]
single frame capture is not yet supported.

**Comment by IsaacZhi** [comment]
Thanks
