### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sunflowersnow** [facebook/Surround360#79]
In the NovelView.cpp file in the 203 row, the index is  wrong (warpOpticalFlow.at<Point2f>(y, x))?
I think warpOpticalFlow's row should be in the range of 0 and width.  but y's range is [0, height).

**Comment by fbriggs** [comment]
opencv's at function takes the arguments in the order y, x. its weird, but that's how opencv does it.

**Comment by sunflowersnow** [comment]
I mean y index out of bounds。
