### ISSUE TITLE
Compiling ffmpeg to include --enable-shared

### ISSUE THREAD

**Issue by s8i** [facebook/Surround360#82]
This seems to be a common issue when compiling a fresh version of ffmpeg
A step by step guide here would be very helpful if anyone has solved this on Ubuntu 14LTS or 16LTS

**Comment by BroadDong** [comment]
When the ffmpeg is compiled,I encounter the issue as follow.Are they the same?
![2016-09-01 17 08 38](https://cloud.githubusercontent.com/assets/20699811/18162617/b7cf780c-7069-11e6-9e85-0936dcf9d511.png)

**Comment by IsaacZhi** [comment]
If you need compiling the code add --enable-shared
libx265 
libvpx
ffmpeg
all need --enable-shared

**Comment by superdog8** [comment]
@IsaacZhi is correct, all the dependencies require --enable-shared when compiling from source. Alternatively install from packages.
