### ISSUE TITLE
Parallax error

### ISSUE THREAD

**Issue by NinaMa17** [facebook/Surround360#86]
I want to know how do you deal with (horizontal)parallax error? For mono panorama, I know it's important to rotate the camera around its entrance pupil to avoid parallax error, and this point usually locates at somewhere between the lens and aperture ring. I've rendered the sample frame provided and didn't notice any parallax error. Is it done by optical flow?

**Comment by fbriggs** [comment]
It works differently for stereo than mono; you want some parallax. Making it seamless is handled by optical flow in our system.
