### ISSUE TITLE
Camera control

### ISSUE THREAD

**Issue by BroadDong** [facebook/Surround360#93]
When I run "./bin/CameraControl -numcams 17 -raw -nbits 8 -shutter 20 -gain 0 -debug", the error is bear as follow. Could you tell me the reason？And how I get the GUI of  the Camera Control?
![camera](https://cloud.githubusercontent.com/assets/20699811/18243941/22284692-7390-11e6-9755-4de0111f76f0.png)

**Comment by mybuddyhoward** [comment]
I'm also seeing the same thing on my end. I've also ran that command under sudo but still the same results. Interested to see if there is a solution or reason for this?

**Comment by malcolmbrown** [comment]
Hi. Did you find a solution to this? I had this section installed successfully and then installed everything else. Since then I get the same error.

**Comment by malcolmbrown** [comment]
Hi. Did you find a solution to this? I had this section installed successfully and then installed everything else. Since then I get the same error. Using Sudo does not fix it.

**Comment by malcolmbrown** [comment]
Hi. I solved this by mounting the RAID using the setup.sh in the scripts folder.

**Comment by aparrapo** [comment]
Thanks for your help @malcolmbrown. Closing this issue.
