### ISSUE TITLE
get_my_data_sunex_intrinsic_xml

### ISSUE THREAD

**Issue by liu666666** [facebook/Surround360#95]
could you please tell me how to create my data sunex_intrinsic.xml， and what  the parameters in this file mean?

**Comment by aparrapo** [comment]
We have step-by-step instructions in:

github.com/facebook/Surround360/blob/master/surround360_render/CALIBRATION.md#intrinsic--barrel-distortion

There are two matrices inside sunex_intrinsic.xml: intrinsic and distortion. You can find more info about each element in each matrix here:

http://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html
